<Project Sdk="Microsoft.NET.Sdk.Web">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SuperAbp.Exam.Admin.Blazor</RootNamespace>
	  <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
	  <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
	  <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
	  <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
	  <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
	  <PreserveCompilationReferences>true</PreserveCompilationReferences>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.0" />
    <PackageReference Include="Blazorise.Bootstrap5" Version="1.6.2" />
    <PackageReference Include="Blazorise.Icons.FontAwesome" Version="1.6.2" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.2" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" Version="9.0.0" />
    <PackageReference Include="DistributedLock.Redis" Version="1.0.3" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lsw.Abp.AspnetCore.Components.Server.AntDesignTheme" Version="0.9.6" />
	  <PackageReference Include="Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite" Version="4.0.0" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SuperAbp.Exam.Admin.Blazor.Client\SuperAbp.Exam.Admin.Blazor.Client.csproj" />
    <ProjectReference Include="..\SuperAbp.Exam.Admin.HttpApi.Client\SuperAbp.Exam.Admin.HttpApi.Client.csproj" />
	  <PackageReference Include="Volo.Abp.Caching.StackExchangeRedis" Version="9.0.0" />
	  <PackageReference Include="Volo.Abp.DistributedLocking" Version="9.0.0" />
	  <PackageReference Include="Volo.Abp.AspNetCore.Mvc.Client" Version="9.0.0" />
	  <PackageReference Include="Volo.Abp.AspNetCore.Authentication.OpenIdConnect" Version="9.0.0" />
	  <PackageReference Include="Volo.Abp.Http.Client.IdentityModel.Web" Version="9.0.0" />
	  <PackageReference Include="Volo.Abp.Autofac" Version="9.0.0" />
	  <PackageReference Include="Volo.Abp.Swashbuckle" Version="9.0.0" />
	  <PackageReference Include="Volo.Abp.AspNetCore.Serilog" Version="9.0.0" />
	  <PackageReference Include="Lsw.Abp.IdentityManagement.Blazor.Server.AntDesignUI" Version="0.9.6" />
	  <PackageReference Include="Lsw.Abp.TenantManagement.Blazor.Server.AntDesignUI" Version="0.9.6" />
	  <PackageReference Include="Lsw.Abp.SettingManagement.Blazor.Server.AntDesignUI" Version="0.9.6" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Logs\**" />
    <Content Remove="Logs\**" />
    <EmbeddedResource Remove="Logs\**" />
    <None Remove="Logs\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="E:\nuget\packages\volo.abp.aspnetcore.mvc.client\9.0.0\contentFiles\any\net9.0\Volo.Abp.AspNetCore.Mvc.Client.abppkg.analyze.json" />
    <Content Remove="E:\nuget\packages\volo.abp.aspnetcore.mvc.ui.multitenancy\9.0.0\contentFiles\any\net9.0\Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy.abppkg.analyze.json" />
    <Content Remove="E:\nuget\packages\volo.abp.aspnetcore.serilog\9.0.0\contentFiles\any\net9.0\Volo.Abp.AspNetCore.Serilog.abppkg.analyze.json" />
    <Content Remove="E:\nuget\packages\volo.abp.http.client.identitymodel.web\9.0.0\contentFiles\any\net9.0\Volo.Abp.Http.Client.IdentityModel.Web.abppkg.analyze.json" />
    <Content Remove="E:\nuget\packages\volo.abp.identity.blazor.server\9.0.0\contentFiles\any\net9.0\Volo.Abp.Identity.Blazor.Server.abppkg.analyze.json" />
    <Content Remove="E:\nuget\packages\volo.abp.settingmanagement.blazor.server\9.0.0\contentFiles\any\net9.0\Volo.Abp.SettingManagement.Blazor.Server.abppkg.analyze.json" />
    <Content Remove="E:\nuget\packages\volo.abp.tenantmanagement.blazor.server\9.0.0\contentFiles\any\net9.0\Volo.Abp.TenantManagement.Blazor.Server.abppkg.analyze.json" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Pages\**\*.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Pages\**\*.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
