name: Deploy Frontend

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd angular-admin
          yarn install

      - name: Build Angular Project
        run: |
          npm run build
          mkdir -p ../publish/Admin
          cp -r dist/* ../publish/Admin/

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: .dist/*
